# Dependencies
markdown: redcarpet
highlighter: pygments
# Permalinks
permalink:        /:title/

encoding: utf-8
# Setup
title:            'நல்ல  வெப்சைட் | Nalla website'
tagline:            'வாழ்வியல் முன்னேற்றத் தளம் -' 
description:      'தமிழில் மற்றொரு தளம்'
url:              http://nallawebsite.com
baseurl:          /
disqus:              nallawebsite
twitter_username:              nallawebsite
author:
  name:           'Jeno Karthic'
  url:            https://twitter.com/nallawebsite

paginate:         5

# Custom vars
version:          1.0

